### ISSUE TITLE
Can't compile for ATtiny84

### ISSUE THREAD

**Issue by franklinvv** [mchr3k/arduino-libs-manchester#13]
This happens when compiling for the ATtiny84 using cores found here:
https://github.com/damellis/attiny/

Apparently, the compiler directives should then be altered in Manchester.cpp in MANRX_SetupReceive().

__AVR_ATtinyX5__ should become __AVR_ATtiny85__
and
__AVR_ATtinyX4__ should become __AVR_ATtiny84__

If not, the library is compiled as if it's for an ATmega328, while the ATtiny84 does not have Timer 2.

**Comment by bodtx** [comment]
I still have the problem with arduino IDE 1.6 and attiny85 @8Mhz
`error: 'TCCR2A' was not declared in this scope
error: 'WGM21' was not declared in this scope
error: 'TCCR2B' was not declared in this scope
error: 'CS21' was not declared in this scope
error: 'OCR2A' was not declared in this scope
error: 'TIMSK2' was not declared in this scope
error: 'OCIE2A' was not declared in this scope
error: 'TCNT2' was not declared in this scope`
