### ISSUE TITLE
Attiny25/45/85 @ 16MHz internal clock

### ISSUE THREAD

**Issue by dragan1alex** [mchr3k/arduino-libs-manchester#29]
Hi!

I have absolutely no idea what kind of voodoo magic you've used in creating this library (I'm new to C programming), but can you please update it to work with the 16MHz internal clock setting on tiny25/45/85?
I think it works fine as it is but the delay becomes half of what it's set to (because of the 2x clock speed).

Cheers
Andrei

**Comment by HrGaertner** [comment]
I think something equal is happening with my digispark (basically attiny85)

Equally what delay() i chosse it is arround 1 second
